services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 81:81
    networks:
      - appnet
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  idp:
    build:
      context: ..
      dockerfile: Dockerfile.dev
    container_name: idp
    ports:
      - 8080:8080
    networks:
      - appnet
    volumes:
      - ../assets:/assets
    env_file:
      - ../.env

  sonarr:
    image: nginx:latest
    container_name: sonarr
    restart: unless-stopped
    ports:
      - 8082:80
    networks:
      - appnet

  jellyfin:
    image: nginx:latest
    container_name: jellyfin 
    restart: unless-stopped
    ports:
      - 8083:80
    networks:
      - appnet


networks:
  appnet:
    driver: bridge
